export const GET_LOCATION_PERMISSION = 'GET_LOCATION_PERMISSION';
export const GET_LOCATION_NAME = 'GET_LOCATION_NAME';
export const GET_CURRENT_WEATHER_DATA = 'GET_CURRENT_WEATHER_DATA';
export const GET_FORECAST_DATA = 'GET_FORECAST_DATA';


export const SET_ERRORS = 'SET_ERRORS';
export const SET_LOADING = 'SET_LOADING';

export const SET_ALERT = 'SET_ALERT';
